hard_tabs = false
tab_spaces = 2
use_small_heuristics = "Max"
unstable_features = true
overflow_delimited_expr = true
where_single_line = true
type_punctuation_density = "Compressed"
trailing_comma = "Never"